import pyttsx3
engine = pyttsx3.init()
engine.say("Jai Shree Raaaam Jai Hanuman Jai Balaji MAAHARAAJ JAI SHREE SHYAM OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAHOM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH OM SHHREEE SHYAAAM DEEVAAAAYE NAMAAAAAAAH  ")
engine.runAndWait()



a = "Gourav"
t = type(a)
print(t)
